import InputList from './3-State/InputList';
import Called from './1-props/Called';
import Array from './20-4-TWENTY-ARRAY/Array';
import SolveArray from './20-5-Actual-Array/SolveArray';
import MyCounter from './21-22-6-MY-NAME-COUNTER/MyCounter';
import Counter from './3-State/Counter';
import Life from './24-7-COMPONENT-LIFECYCLE/Life';
import Intro from './25-8-USEFFECT/Intro';
import Show from './25-8-USEFFECT/Show';
import Strict from './31-9-STRICT-MODE/Stric';
import FetchApi from './32-10-FETCH/FetchApi';
import ReactDev from './33-11-REACT-DEV-TOOLS/ReactDev';
import FavoriteNumber from './34-12-RENDERING/FavoriteNumber';
import List from './35-13-ListRendering/List';
import UserList from './37-14-USER-LIST/UserList';
import UserListT from './37-14-USER-LIST/UserListT';
import Todo from './41-15-TODO/Todo';
import Rule from './43-16-HOOKS-RULE/Rule';
import UseReff from './44-17-USE-REF/UseReff';
import Memo from './46-18-USE-MEMO-HOOK/Memo';
import MemoA from './46-18-USE-MEMO-HOOK/MemoA';
import UseCallback from './47-19-USE-CALLBACK/UseCallback';
import CustomHooks from './48-20-CUSTOM-HOOKS/CustomHooks';
import CustomFetch from './49-21-USEFETCH-HOOK-CUSTOM/CustomFetch';
function App() {
  // 1-return <Called />;
  // 3-return <InputList />;
  // 3-return <Counter />;
  //4- return <Array />;
  //5- return <SolveArray />;
  //6- return <MyCounter />;
  //7- return <Life />;
  //8- return <Intro />;
  // 8-return <Show />;
  // 9-return <Strict />;
  // 10-return <FetchApi />;
  //11- return <ReactDev />;
  //12- return <FavoriteNumber />;
  //13- return <List />;
  // 14-return <UserList />;
  //14 return <UserListT />;
  //15- return <Todo />;
  //16- return <Rule />;
  //17- return <UseReff />
  //18- return <Memo />;
  // 18-return <MemoA />;
  // 19-return <UseCallback />;
  //20- return <CustomHooks />;
  return <CustomFetch />;
}

export default App;
